Repository roualdes/bridgestan, pull requests merged in 2023-06, with the labels that each got.

#128 Python: Warn if user has 5+ copies in .bridgestan
  python/bridgestan/__init__.py
  python/bridgestan/compile.py
  python/bridgestan/model.py
  python/example.py
  python/test/test_stanmodel.py
Labels: python

#132 R: Allow NaN and Inf to be passed in foreign function calls
  R/R/bridgestan.R
  R/tests/testthat/test-bridgestan.R
Labels: R-lang

#140 Add links to documentation of _R functions in C API
  src/bridgestan.h
  src/bridgestanR.h
Labels: documentation

#142 Add warning to R doc about conda
  docs/languages/r.md
Labels: documentation

#143 Docs: Add note on features not available in all interfaces
  docs/languages.rst
Labels: documentation

#141 Update Getting Started documentation
  docs/getting-started.rst
Labels: documentation

#144 Delete extra sentence in R docs
  R/R/bridgestan.R
  R/man/StanModel.Rd
  R/man/StanRNG.Rd
  docs/languages/r.md
Labels: documentation, R-lang

#146 Add Julia function new_rng
  julia/docs/src/julia.md
  julia/src/BridgeStan.jl
  julia/src/model.jl
Labels: julia

#149 Fix: Windows TBB path logic fails if BridgeStan is not yet downloaded
  .github/workflows/main.yaml
  python/bridgestan/__init__.py
  python/bridgestan/compile.py
  python/bridgestan/model.py
  python/example.py
Labels: bug, python
